import { Button } from "@chakra-ui/button";
import { Flex, Heading } from "@chakra-ui/layout";
import Head from "next/head";

export default function Home() {


  return (
    <>
      <Head>
        <title>Style your Tweet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex justify="center" align="center">
        <Heading>Aca va la home</Heading>
        <Button as="a" href="/app" colorScheme="blue">Ir a la app</Button>
      </Flex>

    </>
  );
}
